version: '3.3'

services:
  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: vav134/backendfoodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/mediafiles/
    env_file:
      - .env

  frontend:
    image: vav134/frontendfoodgram:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/mediafiles/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:
